function mse = CalculateAlphaMSE(predictedAlpha, groundTruthAlpha)
%CALCULATEALPHAMSE Calculates the Mean Squared Error between the predicted alpha matte and the ground truth alpha matte.
%
% Inputs:
%   predictedAlpha - The alpha matte generated by the matting algorithm.
%   groundTruthAlpha - The ground truth alpha matte.
%
% Output:
%   mse - The Mean Squared Error between the predicted and ground truth alpha mattes.

% Ensure the alpha mattes are in the correct format
predictedAlpha = double(predictedAlpha) / 255;
groundTruthAlpha = double(groundTruthAlpha) / 255;

% Calculate MSE across the entire image
mse = mean((predictedAlpha(:) - groundTruthAlpha(:)).^2);

end